name: CI for Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        # Cài đặt Microsoft Edge (hoặc Chrome)
        sudo apt update
        sudo apt install -y microsoft-edge-dev  # Hoặc chromium-browser cho Chrome

    - name: Run tests
      run: |
        python -m unittest discover tests
