name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # v3 đã tương thích với Node.js 20

    - name: Set up Python
      uses: actions/setup-python@v4  # v4 đã tương thích với Node.js 20
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Set up Microsoft Edge and EdgeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y microsoft-edge-stable
        sudo apt-get install -y microsoft-edge-dev

    - name: Install EdgeDriver
      run: |
        sudo apt-get install -y msedgedriver

    - name: Run Selenium tests
      run: |
        python tests/test_login.py
