name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # v3 đã tương thích với Node.js 20

    - name: Set up Python
      uses: actions/setup-python@v4  # v4 đã tương thích với Node.js 20
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Set up Microsoft Edge and EdgeDriver
      uses: actions/edge-chromium-driver@main  # Dùng action GitHub để cài EdgeDriver

    - name: Run Selenium tests
      run: |
        python tests/test_login.py
