name: CI for Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        # Cài đặt Chromium
        sudo apt update
        sudo apt install -y chromium-browser

    - name: Run tests
      env:
        DISPLAY: :99  # Thiết lập biến môi trường DISPLAY
      run: |
        # Chạy các tests
        python -m unittest discover tests
