name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip xvfb
        pip install -r requirements.txt

    - name: Install Microsoft Edge and Driver
      run: |
        wget https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/microsoft-edge-dev_131.0.2875.0-1_amd64.deb
        sudo dpkg -i microsoft-edge-dev_131.0.2875.0-1_amd64.deb || sudo apt-get install -f
        wget https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/123.0.2420.97/edgedriver_linux64.zip
        unzip edgedriver_linux64.zip
        sudo mv msedgedriver /usr/local/bin/msedgedriver

    - name: Start local web server
      run: |
        python3 -m http.server 8000 &
        sleep 5  # Đợi server khởi động

    - name: Run tests
      run: |
        # Khởi động Xvfb để tạo một màn hình ảo
        Xvfb :99 & export DISPLAY=:99

        # Chạy các bài kiểm thử với URL server cục bộ
        python3 tests/test_signup.py