name: Selenium Login Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager
      continue-on-error: true  # Thêm để tiếp tục khi gặp lỗi

    - name: Install Microsoft Edge
      run: |
        sudo apt update
        sudo apt install -y microsoft-edge-stable
      continue-on-error: true  # Thêm để tiếp tục khi gặp lỗi

    - name: Install Microsoft Edge WebDriver
      run: |
        sudo apt install -y microsoft-edge-dev
        sudo apt install -y microsoft-edge-dev-webdriver
        export PATH=$PATH:/usr/lib/microsoft-edge-dev
      continue-on-error: true  # Thêm để tiếp tục khi gặp lỗi

    - name: Check Edge version
      run: |
        microsoft-edge --version  # Kiểm tra phiên bản Edge đã cài đặt để xem có vấn đề gì không
      continue-on-error: true

    - name: Run Selenium tests
      run: |
        python tests/test_login.py
      continue-on-error: true  # Cho phép tiếp tục nếu có lỗi

    - name: Debugging logs
      run: dmesg | tail  # Ghi log hệ thống để debug thêm lỗi nếu có
