name: Selenium Login Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Sử dụng phiên bản Python 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Install Microsoft Edge
      run: |
        sudo apt update
        sudo apt install -y microsoft-edge-stable

    - name: Install Microsoft Edge WebDriver
      run: |
        sudo apt install -y microsoft-edge-dev
        sudo apt install -y microsoft-edge-dev-webdriver
        export PATH=$PATH:/usr/lib/microsoft-edge-dev

    - name: Run Selenium tests
      run: |
        python tests/test_login.py
