name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget

          # Cài đặt Microsoft Edge Dev
          wget https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/microsoft-edge-dev_135.0.xxxx.x-1_amd64.deb
          sudo dpkg -i microsoft-edge-dev_135.0.xxxx.x-1_amd64.deb || sudo apt install -f

      - name: Run tests
        run: python3 tests/test_login.py
